In [1]:
from sklearn.model_selection import cross_val_score, GridSearchCV, KFold
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, RidgeCV
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, AdaBoostRegressor, BaggingRegressor
from sklearn.svm import SVR, LinearSVR
from sklearn.linear_model import ElasticNet, SGDRegressor, BayesianRidge
from sklearn.kernel_ridge import KernelRidge
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
import pickle
def getData(dataFilePath):
    """读取数据"""
    data = pickle.load(open(dataFilePath, 'rb'))

    return data 

In [101]:
import numpy as np
def cv_rmse(model, X, y):
    # cross_val_score函数用法：https://www.cnblogs.com/lzhc/p/9175707.html
    rmse = np.sqrt(cv_mse(model, X, y))
    return rmse

def cv_mse(model, X, y):
    rmse = -cross_val_score(model, X, y, scoring="neg_mean_squared_error", cv=5)
    return rmse

In [7]:
dataFilePath = r"C:\Study\github\Lookoops\tool\毕设代码\data\samples-data.data"
labelsFilePath = r"C:\Study\github\Lookoops\tool\毕设代码\data\samples-data-labels.data"
X = getData(dataFilePath)
y = getData(labelsFilePath)
Y = y.reshape(1, len(y))[0]
print(X)
print("*"*20)
print(Y)

[[   0.      0.      0.      0.      0.  ]
 [  42.18 -142.08 -130.84  233.82  124.2 ]
 [ -60.    168.3  -121.16  -56.34  -77.  ]
 [ 285.96 -285.3   -98.88 -228.72   69.96]
 [ 144.66 -222.36 -160.4   290.82  -10.96]
 [ -61.56 -117.66 -111.24  153.24  -84.12]
 [  37.92  -66.42   27.56 -154.2   110.8 ]
 [-169.74  243.78   16.8  -269.46 -116.92]
 [  12.96   20.46 -194.68  175.86  181.8 ]
 [ 263.04  281.76  -30.56   -3.6  -105.56]
 [ 195.42 -167.76 -216.36  242.16   15.8 ]
 [ -82.92   46.44 -260.96  200.1   144.08]
 [ 231.18 -240.72   69.2   -21.6   173.08]
 [-126.12  114.06   49.44 -126.54   59.92]
 [ 125.82  -81.54  -17.92 -112.38 -134.52]
 [-267.48   -7.14   -3.48   91.8  -132.68]
 [  96.6   -47.22 -237.88  134.16  195.88]
 [ -26.88 -128.88  -36.6  -252.84  -46.92]
 [ 219.18  239.7  -286.04   15.66 -174.8 ]
 [ 259.86 -216.6  -171.24 -197.46  -61.72]
 [-208.86  274.26 -224.88  -64.14  -34.32]
 [-235.32  193.14  -60.64   52.32 -167.36]
 [-111.42 -276.54   94.44  -91.5    36.84]
 [-150.72  

In [50]:
models = [LinearRegression(),
          Ridge(), # http://www.cnblogs.com/pinard/p/6023000.html
          Lasso(alpha=0.01,max_iter=10000), # https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html
          RandomForestRegressor(), # https://scikit-learn.org/dev/modules/generated/sklearn.ensemble.RandomForestRegressor.html
          GradientBoostingRegressor(), # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingRegressor.html
          SVR(), # https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR
          LinearSVR(), # https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVR.html
          ElasticNet(alpha=0.001,max_iter=10000), # https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.ElasticNet.html
          SGDRegressor(max_iter=10000,tol=1e-3), # https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor.html
          BayesianRidge(), # 
          KernelRidge(alpha=0.6, kernel='polynomial', degree=2, coef0=2.5), # https://scikit-learn.org/stable/modules/generated/sklearn.kernel_ridge.KernelRidge.html
         ExtraTreesRegressor(), # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesRegressor.html
          XGBRegressor(), 
          AdaBoostRegressor(n_estimators=50), # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostRegressor.html
          BaggingRegressor(), # https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingRegressor.html
          DecisionTreeRegressor(), #https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
          KNeighborsRegressor()] # https://scikit-learn.org/0.18/modules/generated/sklearn.neighbors.KNeighborsRegressor.html

In [103]:
names = ["LR", "Ridge", "Lasso", "RF", "GBR", "SVR", "LinSVR", "Ela","SGD","Bay","Ker","Extra","Xgb", "AdaBoost", "Bagging", "DT", "KN"]
for name, model in zip(names, models):
    score = cv_rmse(model, X, Y)
    print("{}: {:.6f}, {:.4f}".format(name,score.mean(), score.std()))

LR: 730.484932, 139.2713
Ridge: 730.483928, 139.2717
Lasso: 730.484824, 139.2713
RF: 729.002173, 181.9809
GBR: 782.192409, 113.5257
SVR: 661.252776, 182.2134
LinSVR: 28991.287066, 6662.4788
Ela: 730.484914, 139.2713
SGD: 286743911699273.562500, 68731878454941.1016
Bay: 623.333074, 178.1188
Ker: 4670.402649, 3445.9364
Extra: 658.341334, 136.1935
Xgb: 789.280481, 85.1577
AdaBoost: 777.094022, 87.3443
Bagging: 763.008852, 115.6027
DT: 1003.386169, 176.9465
KN: 690.915668, 169.9492


In [78]:
import pandas as pd
class grid():
    def __init__(self, model):
        self.model = model
        
    def grid_train(self, X, y, train_para):
        grid_search = GridSearchCV(self.model, train_para, cv=5, scoring="neg_mean_squared_error", return_train_score=True)
        grid_search.fit(X, y)
        print(grid_search.best_params_, np.sqrt(-grid_search.best_score_)) # 打印最好的结果
        grid_search.cv_results_['mean_test_score'] = np.sqrt(-grid_search.cv_results_['mean_test_score'])
#         print(pd.DataFrame(grid_search.cv_results_)[['params','mean_test_score','std_test_score']])

In [53]:
# grid(Lasso()).grid_train(X,Y,{'alpha': [0.002, 0.0003, 0.00035, 0.0004,0.0005,0.0007,0.0006,0.0009,0.0008], 'max_iter':[10000]})

In [54]:
# grid(Ridge()).grid_train(X,Y,{'alpha':[i for i in range(10, 20)]})

In [97]:
grid(RandomForestRegressor()).grid_train(X, Y,{'max_depth':[i for i in range(1, 10)]+[None], 'n_estimators':[i for i in range(10, 120, 10)]})

{'max_depth': 1, 'n_estimators': 20} 686.9222317577


In [42]:
grid(GradientBoostingRegressor()).grid_train(X,Y,{'learning_rate':[float(i/10) for i in range(1, 10)], 'n_estimators':[i for i in range(50, 150, 10)]})

{'learning_rate': 0.2, 'n_estimators': 50} 761.9353750810606


In [100]:
grid(SVR()).grid_train(X,Y,
                       {
                           'kernel':['rbf'], 
                           'gamma':[0.0001, 0.0005, 0.001,0.005, 0.01, 0.05, 0.1, 0.5],
                           'epsilon':[0.0005, 0.001,0.005, 0.01, 0.05, 0.1, 0.5, 1, 10, 20, 50, 100, 500, 1000, 5000]
                       })

{'epsilon': 1000, 'gamma': 0.0001, 'kernel': 'rbf'} 639.0902002451987


In [58]:
grid(LinearSVR()).grid_train(X,Y,{'epsilon':[0.0005, 0.001,0.005, 0.01, 0.05, 0.1, 0.5], 'loss':['epsilon_insensitive', 'squared_epsilon_insensitive']})

{'epsilon': 0.01, 'loss': 'squared_epsilon_insensitive'} 15177.775903622676


In [59]:
grid(GradientBoostingRegressor()).grid_train(X,Y,{'learning_rate':[float(i/10) for i in range(1, 10)]})

{'learning_rate': 0.2} 770.716243656305


In [60]:
grid(ElasticNet()).grid_train(X,Y,{'alpha':[0.0005, 0.001,0.005, 0.01, 0.05, 0.1, 0.5],'l1_ratio':[0.08,0.1,0.3,0.5,0.7],'max_iter':[10000]})

{'alpha': 0.5, 'l1_ratio': 0.08, 'max_iter': 10000} 744.3100332644116


In [64]:
# 报错
# grid(SGDRegressor()).grid_train(X,Y,{'alpha':[0.005, 0.01, 0.05, 0.1,0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5],'l1_ratio':[0.08,0.1,0.3,0.5,0.7, 0.8, 0.9, 1]})

In [79]:
grid(BayesianRidge()).grid_train(X,Y, {'alpha_1':[1e-6, 5e-6, 1e-5], 'alpha_2':[5e-7, 1e-6], 'tol':[0.0001, 0.0005, 0.001, 0.002, 0.005, 0.01]})

{'alpha_1': 1e-06, 'alpha_2': 1e-06, 'tol': 0.0001} 648.2003756817544


In [23]:
# grid(KernelRidge()).grid_train(X,Y,{'alpha':[0.05, 0.1, 0.3,0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1, 5], 'kernel':['polynomial'], 'coef0':[1, 1.2, 1.5, 1.6, 1.8, 1.9, 2, 2.2, 2.5, 3]})

In [88]:
grid(ExtraTreesRegressor()).grid_train(X, Y,{'min_samples_split':[i/10 for i in range(1, 10)], 'min_samples_leaf':[i/10 for i in range(1, 5)]})

{'min_samples_leaf': 0.4, 'min_samples_split': 0.1} 652.7785167854623


In [89]:
grid(AdaBoostRegressor()).grid_train(X, Y, {'n_estimators':[i for i in range(10, 100, 10)], 'learning_rate':[i/10 for i in range(1, 10)]})

{'learning_rate': 0.3, 'n_estimators': 50} 710.2285467477809


In [92]:
grid(BaggingRegressor()).grid_train(X, Y, {'n_estimators':[i for i in range(1, 50)]})

{'n_estimators': 7} 646.5600072210289


In [93]:
grid(DecisionTreeRegressor()).grid_train(X, Y, {})

{} 1012.1550463240105


In [95]:
grid(KNeighborsRegressor()).grid_train(X, Y, {'n_neighbors':[i for i in range(1, 20)]})

{'n_neighbors': 19} 668.2343036656489
